
title: Experiences
desctiption: This is a blog about Life.
url: http://webjeda.com/
permalink: ':title/'

markdown: kramdown
baseurl: ""


sass:
    style: compressed

  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: deepblocks
# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]

gems: [jekyll-paginate, jekyll-seo-tag]



